{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.3.3.aar",
          "url": "runtime-livedata-1.3.3.aar",
          "size": 7554,
          "sha512": "ce4b3e2248a85634be4fb7df16a39103fb5d977ff0b758bbf01c222b749c920a2d739257542f200e7b540286c3495dc2f2470a0a726e67ab75d96fa83c41931c",
          "sha256": "4c15e2835e78e7b63006903b6a5e38536f5fb87da42c2c11c99f95a413c61c09",
          "sha1": "df9b21c82150421a0e178084daae39664b0576d8",
          "md5": "c9d4a8f45c188ece23a6a96b3ca373fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.3.3.aar",
          "url": "runtime-livedata-1.3.3.aar",
          "size": 7554,
          "sha512": "ce4b3e2248a85634be4fb7df16a39103fb5d977ff0b758bbf01c222b749c920a2d739257542f200e7b540286c3495dc2f2470a0a726e67ab75d96fa83c41931c",
          "sha256": "4c15e2835e78e7b63006903b6a5e38536f5fb87da42c2c11c99f95a413c61c09",
          "sha1": "df9b21c82150421a0e178084daae39664b0576d8",
          "md5": "c9d4a8f45c188ece23a6a96b3ca373fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-1.3.3-sources.jar",
          "url": "runtime-livedata-1.3.3-sources.jar",
          "size": 1824,
          "sha512": "12fdf7b2e70e16d3bcb59966d8e05b36b9698923cb467e376ee542aa1c98f87996f1b204a688dd2f783701a67055260ab797b6bc70e046df095bb535c7d505a2",
          "sha256": "2940823fd4f14afcab6a5aa9ad79f2a353f78c1312f9251fdd7c017ad171cff9",
          "sha1": "a36eb1d628eb1d76e540e9357a1330ade67e328c",
          "md5": "9900ddee4f1294723a75e9a0837241e3"
        }
      ]
    }
  ]
}